(map load '("strings.arc"
            "cookies.arc"
            "parallel.arc"
            "pprint.arc"
            "code.arc"
            "html.arc"
            "srv.arc"
            "app.arc"
            "json.arc"
            "recaptcha.arc"
            "email.arc"
            "prompt.arc"
            "memorable.arc"))
